Proposal: New repository structure
container-images/container-image-template-old pull request #15
Opened 2017-06-14 12:41 UTC by rpitonak

This PR changing the repository structure.
- every version directory of service now contains directories for every distribution (Fedora, CentOS, RHEL).
- There is one set of the tests for every version.
- Every image has "root" directory, which contains help file   

Open question:
  - where will be common files for every distribution (or version?) placed?

Your feedback is welcome!

2017-06-15 08:46 UTC, TomasTomecek commented
fuf, this is massive: might be even worth talking about this in person

2017-06-15 08:55 UTC, TomasTomecek requested changes
I still prefer we talk about this in person since this is so big.

Edit: ideally I would love to hook CI (out of scope of this PR) so we can be sure that our template can built and tests are passing. Yes, even on template.

2017-06-15 08:55 UTC, TomasTomecek commented on Makefile
> +	cd $(VERSION)/$(TARGET) && make build VERSION=$(VERSION)
so `build` will build only a single image? could be interesting to build all of them

2017-06-15 08:55 UTC, TomasTomecek commented on x.y/centos/Dockerfile
> +LABEL MAINTAINER ...
can we have here all required labels mentioned -- ideally in a form so the dockerfile builds?

2017-06-15 08:55 UTC, TomasTomecek commented on x.y/rhel/examples/run_in_cluster.md
> +You can use this image to start clustered version of `$service`.
I would get rid of this file since we have help files.

2017-06-15 08:55 UTC, TomasTomecek commented on README.md
>   * `README.md` — global documentation for the whole service
We should make sure that people are pointed to help files so we don't duplicate.

2017-06-15 08:55 UTC, TomasTomecek commented on README.md
>   * `README.md` — version specific documentation
Similar as above: make sure we link to help file and let's make the readme short.

2017-06-15 12:06 UTC, TomasTomecek commented on Makefile
> +	cd $(VERSION)/$(TARGET) && make build VERSION=$(VERSION)
We just agreed we would only build the latest version -- we can always improve this later.

2017-06-19 11:58 UTC, rpitonak commented
Fixed, can you check it again? @TomasTomecek

2017-06-20 08:29 UTC, TomasTomecek commented
Since this is so big, let's merge and address potential issues individually.

2017-06-20 08:29 UTC, merged