Add make doc
container-images/container-image-template-old pull request #22
Opened 2017-06-21 12:24 UTC by kosciCZ

This PR would add make doc functionality - a convenient way to convert help.md to help.1, and to do that with every build.

2017-06-22 10:10 UTC, TomasTomecek requested changes

2017-06-22 10:10 UTC, TomasTomecek commented on x.y/Makefile
> +PHONY: .doc .run .build .test
ehm, why are dots here? (I know you haven't introduced this, can we have it fixed?)

2017-06-22 10:10 UTC, TomasTomecek commented on x.y/centos/Makefile
> +	go-md2man -in=./root/help.md -out=./root/help.1
we should also change dockerfile (probably even the file structure) so we don't add help.md inside image since help.1 will be there

2017-06-26 06:28 UTC, kosciCZ commented on x.y/centos/Makefile
> +	go-md2man -in=./root/help.md -out=./root/help.1
I agree, this should be changed. What do you think the new file structure should be? Moving help.md out of the root folder into version/base/ folder? That would make most sense to me, since root folder will probably contain other files and copying one by one to avoid copying help.md would make little sense.

2017-06-28 07:33 UTC, TomasTomecek commented on x.y/centos/Makefile
> +	go-md2man -in=./root/help.md -out=./root/help.1
I would put the `help.md` to `files/` directory and render `help.1` to `root/` directory. WDYT?

2017-07-10 10:55 UTC, merged