Dockerfile.template designed by hhorak and me.
container-images/container-image-template-old pull request #3
Opened 2017-01-12 14:32 UTC by phracek

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

Together with Honza Horak, we have designed and Dockerfile.template which could help beginners to start with Docker.
@hhorak: Thanks for help.

I would be welcome for your feedback. Does it make sense for you? Please keep it mind, if you are docker newcomer, you will want some help at the beginning.

2017-01-13 10:51 UTC, TomasTomecek requested changes
A couple nits, one typo, one grammar issue; nothing important. Nicely done!

2017-01-13 10:51 UTC, TomasTomecek commented on Dockerfile.template
> +# Command which will be start service during command `docker run`
`which will start the service`

2017-01-13 10:51 UTC, TomasTomecek commented on Dockerfile.template
> +# VOLUME mounts host dir into container dir. It is specified by parameter -v <host_directory>"<container_directory>
`<host_dir>:<cont_dir>`, not `"`

2017-01-13 10:51 UTC, TomasTomecek commented on Dockerfile.template
> +# USER 89
I'm assuming that the user is created when postfix package is installed, hence I would prefer name over uid. Also we should cover scenario, when the "user account" is not created.

2017-01-13 10:51 UTC, TomasTomecek commented on Dockerfile.template
> +#       description="Some further description." \
Can you please fill the further description since this is a real example?

2017-01-13 10:51 UTC, TomasTomecek commented on Dockerfile.template
> +# Provide some Dockerfile description, like is mentioned below
I like this section, would be awesome if had this as a machine readable metadata.

2017-01-13 10:56 UTC, eliskasl commented
I didn't get the commenting :) How about removing comments (#) from every line that is actually not a comment? It would make it a bit more readable. Since it's a template I guess nobody will actually attempt to run it :)
Anyway good work, I like it.

2017-01-13 10:58 UTC, eliskasl commented
Btw, you might want to tag others when requesting feedback, not sure if anyone outside the Admin group gets a notification when a PR is created.

2017-01-15 18:13 UTC, TomasTomecek commented
> Btw, you might want to tag others when requesting feedback, not sure if anyone outside the Admin group gets a notification when a PR is created.

8 people watch this repo, so hopefully they are getting the notifications. Definitively a good suggestion though.

2017-01-16 08:33 UTC, phracek commented on Dockerfile.template
> +# Provide some Dockerfile description, like is mentioned below
An example would be welcome, I will do it. Thanks for tips and review.

2017-01-16 09:09 UTC, phracek commented
@whitel @james-antill @asamalik Hi folks, I did a couple of updates. Feel free to comment it.

2017-01-16 09:45 UTC, TomasTomecek reviewed
2 more tiny docs nits. Otherwise LGTM, nicely done, Peťo!

2017-01-16 09:45 UTC, TomasTomecek commented on Dockerfile.template
> +VOLUME ['/var/spool/postfix']
I know that I'm such a nitpicker -- I should have mention it in previous round, I'm sorry about that.

This is not entirely true. `VOLUME` instruction creates unnamed volume in `/var/lib/docker/volumes` and mounts it inside a container -- so your data do NOT persist in the container. Doing `docker run -v ...` is just an override. Hence, could we update the comment to:

```
VOLUME instruction creates unnamed volume and mounts it to the provided path, you can override this behavior by mounting a selected host directory into container: "-v <host_directory>:<container_directory>"
```

2017-01-16 09:45 UTC, TomasTomecek commented on Dockerfile.template
> +# This exposes port from container to host. Specify it during `docker run` as parameter -p 25:10025
Please also mention that the format is `<host>:<container>`.

2017-01-16 13:56 UTC, phracek commented on Dockerfile.template
> +VOLUME ['/var/spool/postfix']
No problem. I would like to create a template which can be useful for the others. So better explanation is welcome.

2017-01-16 15:52 UTC, TomasTomecek approved these changes

2017-01-16 19:23 UTC, merged