Run tests in the container
container-images/container-image-template-old pull request #38
Opened 2017-08-24 11:16 UTC by rpitonak

Tests now running inside the container, but still failing because of 'baseruntime' and 'microdnf' tests (Issue [#45](https://github.com/fedora-modularity/meta-test-family/issues/45))

Also failing because of behave tests, @jscotka can you take a look on it?
```
make[3]: Leaving directory '/src/tests'
cd ../../behave-tests; VERSION=x.y MODULE=docker URL="docker=image:x.y" make all
make[3]: Entering directory '/src/behave-tests'
behave
make[3]: behave: Command not found
```

2017-08-24 11:57 UTC, TomasTomecek commented
you may need to install `python2-behave`

2017-08-24 12:19 UTC, TomasTomecek commented
I propose to remove behave tests from this repository. Once that's done, I think the test suite should be passing just fine.

We should also polish tests in `tests/`, I'll open an issue for that.

2017-08-24 13:50 UTC, TomasTomecek requested changes
looks good! tests did pass.

follow-up work: https://github.com/container-images/container-image-template/issues/39

2017-08-24 13:50 UTC, TomasTomecek commented on tests/Makefile
> +CMD=avocado run --show-job-log
I guess let's remove the `--show-job-log` and just mention it in comment

2017-08-25 10:47 UTC, TomasTomecek commented
In this case, I consider https://github.com/fedora-modularity/meta-test-family/issues/64 to be a blocker, since we are not able to figure out why the tests failed.

2017-09-12 10:33 UTC, phracek commented on x.y/centos/Makefile
>  	cd ../../tests; VERSION=$(VERSION) DOCKERFILE="../centos/Dockerfile" MODULE=docker URL="docker=$(IMAGE_NAME):$(VERSION)" make all
This is wrong reference to Dockerfile. It should be `../x.y/centos/Dockerfile`

2017-09-12 10:34 UTC, phracek commented on x.y/fedora/Makefile
>  	cd ../../tests; VERSION=$(VERSION) DOCKERFILE="../fedora/Dockerfile" MODULE=docker URL="docker=$(IMAGE_NAME):$(VERSION)" make all
This is wrong reference to Dockerfile. It should be `../x.y/fedora/Dockerfile`

2017-09-12 10:34 UTC, phracek commented on x.y/rhel/Makefile
>  	cd ../../tests; VERSION=$(VERSION) DOCKERFILE="../rhel/Dockerfile" MODULE=docker URL="docker=$(IMAGE_NAME):$(VERSION)" make all
This is wrong reference to Dockerfile. It should be `../x.y/rhel/Dockerfile`

2017-09-12 10:34 UTC, phracek commented on x.z/centos/Makefile
>  	cd ../../tests; VERSION=$(VERSION) DOCKERFILE="../centos/Dockerfile" MODULE=docker URL="docker=$(IMAGE_NAME):$(VERSION)" make all
This is wrong reference to Dockerfile. It should be `../x.y/centos/Dockerfile`

2017-09-12 10:34 UTC, phracek commented on x.z/fedora/Makefile
>  	cd ../../tests; VERSION=$(VERSION) DOCKERFILE="../fedora/Dockerfile" MODULE=docker URL="docker=$(IMAGE_NAME):$(VERSION)" make all
This is wrong reference to Dockerfile. It should be `../x.z/fedora/Dockerfile`

2017-09-12 10:35 UTC, phracek commented
I will file a new PR based on this.

2017-09-13 11:19 UTC, TomasTomecek commented
addressed in the other pr

2017-09-13 11:19 UTC, closed without merging